version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/tarafirst_user_management
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install_dep.sh
      timeout: 300
      runas: root

    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 600
      runas: root
