services:
  user_management:
    image: ${DOCKER_IMAGE}:${IMAGE_TAG}
    container_name: user_management_service
    ports:
      - "8000:8000"
    restart: always
    command: uvicorn Tara.asgi:application --host 0.0.0.0 --port 80000
    env_file:
      - .env
    networks:
      - taranet
    healthcheck:
      test: [ "CMD-SHELL", "python -c 'import urllib.request; exit(0) if urllib.request.urlopen(\"http://localhost:8000/user_management/test/\").status == 200 else exit(1)'" ]
      interval: 30s
      timeout: 5s
      retries: 5
networks:
  taranet:
    driver: bridge