# Generated by Django 5.0.4 on 2025-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='default_session',
            field=models.BooleanField(default=False, help_text='Indicates if this is the default session for the user'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.UniqueConstraint(condition=models.Q(('default_session', True)), fields=('user',), name='unique_default_session_per_user'),
        ),
    ]
