# Generated by Django 5.0.4 on 2025-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_usersession_default_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google OAuth'), ('both', 'Both Email and Google')], default='email', help_text='Authentication method used by the user', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='google_name',
            field=models.CharField(blank=True, help_text='Name from Google account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='google_user_id',
            field=models.CharField(blank=True, help_text="Google's unique user ID", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='registration_flow',
            field=models.CharField(blank=True, choices=[('module', 'Module-based'), ('service', 'Service-based'), ('standard', 'Standard'), ('google_oauth', 'Google OAuth')], help_text='Tracks which registration flow the user started from', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='users',
            constraint=models.UniqueConstraint(condition=models.Q(('google_user_id__isnull', False)), fields=('google_user_id',), name='unique_google_user_id_when_not_null'),
        ),
    ]
