# Generated by Django 5.0.4 on 2025-10-06 07:54

import usermanagement.helpers
import usermanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_users_auth_provider_users_google_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_address',
            field=models.JSONField(blank=True, default=dict, help_text='Personal address details in JSON format'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, storage=usermanagement.models.PrivateS3Storage(), upload_to=usermanagement.helpers.profile_picture_upload_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_address',
            field=models.JSONField(blank=True, default=dict, help_text='Work address details in JSON format'),
        ),
    ]
