# Generated by Django 5.0.4 on 2025-10-07 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_userprofile_date_of_birth_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number with 10-15 digits, optionally starting with +', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
